name: Shell commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name:  Python command
        run: |
          import platform
          print(platform.processor())
        shell: python
